version: "3.7"

services:
  web:
    image: bitcoinscala/wallet-server-ui:0.0.1-ae89fdcb-SNAPSHOT
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      ORACLE_SERVER_API_URL: "http://10.21.21.101:9999/"
      TOR_PROXY: socks5://${TOR_PROXY_IP}:${TOR_PROXY_PORT}
    ports:
      - "3100:3001"
    networks:
      default:
        ipv4_address: 10.21.21.100
    depends_on: 
      - walletserver
  walletserver:
    image: bitcoinscala/bitcoin-s-server:1.8.0-38-0b9500f4-SNAPSHOT
    user: "1000:1000"
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/wallet:/home/bitcoin-s/.bitcoin-s
    environment:
      BITCOIN_S_KEYMANAGER_ENTROPY: $APP_SEED  
      BITCOIN_S_PROXY_ENABLED: false
      BITCOIN_S_TOR_ENABLED: false
      BITCOIN_S_TOR_PROVIDED: true
      BITCOIN_S_DLCNODE_PROXY_ENABLED: true
      BITCOIN_S_DLCNODE_PROXY_SOCKS5: "${TOR_PROXY_IP}:${TOR_PROXY_PORT}"
      BITCOIN_S_BITCOIND_HOST: $BITCOIN_IP
      BITCOIN_S_BITCOIND_PORT: $BITCOIN_RPC_PORT
      BITCOIN_S_BITCOIND_USER: $BITCOIN_RPC_USER
      BITCOIN_S_BITCOIND_PASSWORD: $BITCOIN_RPC_PASS
    networks:
      default:
        ipv4_address: 10.21.21.101